# Generated by Django 5.0.2 on 2024-03-02 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_comuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('fundacao', models.PositiveIntegerField(help_text='Ano de fundação do clube', verbose_name='Fundação')),
                ('divisao', models.CharField(choices=[('A', 'Serie A'), ('B', 'Serie B'), ('C', 'Serie C'), ('D', 'Serie D'), ('E', 'Serie E')], default='S', max_length=64)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros_comuns.cidade')),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('numero_camisa', models.PositiveIntegerField()),
                ('foto', models.ImageField(null=True, upload_to='jogadores')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Futebolarte.clube')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
